config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tasks, defaults: { format: :json }

  resources :boards, only: %i[show index]
  resources :posts_widgets, only: [] do
    resources :posts, only: %i[edit update new create show increase_like] do
      member do
        get :increase_like
      end
    end
  end

  root to: 'boards#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# frozen_string_literal: true

class Board < ApplicationRecord
  has_many :widgets
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :title, :body, presence: true

  belongs_to :widget

  before_create do |post|
    post.likes ||= 0
    post.avatar_name = %w[el_primo penny leon].sample
  end

  after_create :update_all_relevances

  def self.update_all_relevances
    Post.all.map(&:update_relevance!)
  end

  def update_all_relevances
    self.class.update_all_relevances
  end

  def update_relevance!
    self.relevance = likes * 100 / Post.sum(:likes).to_f
    self.relevance ||= 0
    save
  end
end

app/models/posts_widget.rb
# frozen_string_literal: true

class PostsWidget < Widget
  has_many :posts, foreign_key: :widget_id
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
end

app/models/tasks_widget.rb
# frozen_string_literal: true

require 'net/http'

class TasksWidget < Widget
  def tasks
    url = URI.parse('http://localhost:3001/tasks')
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) do |http|
      http.request(req)
    end
    JSON.parse(res.body)[0..5]
  end
end

app/models/video_widget.rb
# frozen_string_literal: true

class VideoWidget < Widget
end

app/models/widget.rb
# frozen_string_literal: true

class Widget < ApplicationRecord
  belongs_to :board
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

class BoardsController < ApplicationController
  before_action :set_board, only: %i[show]

  def index
    redirect_to Board.first
  end

  def show
    @widgets = @board.widgets
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:name)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update increase_like]
  before_action :set_widget

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.widget = @widget

    if @post.save
      redirect_to @widget.board, notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @widget.board, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def increase_like
    @post.increment!(:likes)
    # Post.update_all_relevances

    respond_to do |format|
      format.js { render layout: false } # Add this line to you respond_to block
    end
  end

  private

  def set_widget
    @widget = Widget.find(params[:posts_widget_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :status)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def edit; end

  def create
    @task = Task.new(task_params)

    respond_to do
      if @task.save
        render :show, status: :created, location: @task
      else
        render json: @task.errors, status: :unprocessable_entity
      end
    end
  end

  def update
    respond_to do
      if @task.update(task_params)
        render :show, status: :ok, location: @task
      else
        render json: @task.errors, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @task.destroy
    head :no_content
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :location, :scheduled_to)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/boards_helper.rb
# frozen_string_literal: true

module BoardsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
<% if board.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

    <ul>
        <% board.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
</div>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

app/views/boards/_increase_like.html.erb
<%= link_to content_tag(:i, "%s likes" % post.likes, class: 'ni ni-like-2'), increase_like_posts_widget_post_path(widget, post), remote: true %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boards</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @boards.each do |board| %>
        <tr>
            <td><%= board.name %></td>
            <td><%= link_to 'Show', board %></td>
            <td><%= link_to 'Edit', edit_board_path(board) %></td>
            <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<div class="card-deck" id='card-deck'>
    <% @widgets.map do |widget| %>
    <% if widget.is_a?(PostsWidget) %>
    <div class="card">
        <div class="card-header">
            <h5 class="h3 mb-0">
                <%= widget.name %> (<%= widget.posts.where(status: 1).count %>)
                <%= 
                    link_to ("<i class='fas fa-user-edit'></i>").html_safe ,
                    new_posts_widget_post_path(widget) 
                %>
            </h5>
        </div>
        <div class="card-body">
            <div class="mb-1">
                <% widget.posts.where(status: 1).order(created_at: :desc).limit(4).map do |post| %>
                <div class="media media-comment">
                    <%= image_tag("avatars/#{post.avatar_name}.png", class: "avatar avatar-lg media-comment-avatar rounded-circle") %>
                    <div class="media-body">
                        <div class="media-comment-text">
                            <h6 class="h5 mt-0"><%= post.username %></h6>
                            <p class="text-sm lh-160">
                                <%= post.title.html_safe%>
                            </p>
                            <div class="likes" id="post-<%= post.id%>">
                                <%= render partial: 'increase_like', locals: { post: post, widget: widget } %>
                            </div>

                            <div class="relevance">
                                <i class="ni ni-chart-bar-32"></i>
                                <span class="text-muted"><%= "%5.2f" % post.relevance %>% relevância</span>
                            </div>

                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
    <% elsif widget.is_a?(TasksWidget) %>
    <div class="card">
        <div class="card-header">
            <h5 class="h3 mb-0"><%= widget.name %></h5>
        </div>
        <div class="card-body p-0">

            <ul class="list-group list-group-flush">
                <% widget.tasks.map do |task| %>
                <li class="checklist-entry list-group-item flex-column align-items-start py-4 px-4">
                    <div class="checklist-item checklist-item-<%= task['task_type'] %>">
                        <div class="checklist-info">
                            <h5 class="checklist-title mb-0"><%= task['title'] %></h5>
                            <small><%=  Time.zone.parse(task['scheduled_to']).strftime("%d/%m/%Y às %I:%M%p") %></small>
                        </div>
                    </div>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
    <% elsif widget.is_a?(VideoWidget) %>
    <div class="card">
        <div class="card-header">
            <h5 class="h3 mb-0"><%= widget.name %></h5>
        </div>
        <div class="card-body p-0">
            <iframe id="ytplayer" type="text/html" width="100%" height="100%" src="http://www.youtube.com/embed/TfSm7v8zcYc?autoplay=1&origin=http://example.com" frameborder="0" />
        </div>
    </div>
    <% end %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Dashboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= yield %>
</body>

</html>

app/views/posts/_form.html.erb
<%= form_with(model: [@widget, post]) do |form| %>

<% if post.errors.any? %>
<div class="alert alert-warning alert-dismissible fade show">
    <h2> <%= t('errors.forms.title', count: post.errors.count) %></h2>
    <ul>
        <% post.errors.each do |error| %>
        <li>
            <span class="alert-text"><strong><%= t(:warning)%></strong> <%= error.full_message %></span>
        </li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="card">
    <div class="card-header">
        <h3 class="mb-0"> <%= t('.title') %> </h3>
    </div>
    <div class="card-body">
        <div class="form-group field">
            <%= form.label :title, class: "form-control-label" %>
            <%= form.text_field :title, required: true, placeholder: "digite o título do post", class: "form-control" %>

        </div>
        <div class="form-group field">
            <%= form.label :status, class: "form-control-label" %>
            <%= form.select :status, [["Rascunho", "1"], ["Publicado", "2"], ["Removido", "3"]], { required: true}, {class: "form-control"} %>

        </div>

        <div class="form-group field">
            <%= form.label :body, class: "form-control-label" %>
            <%= form.text_area :body, required: true, class: "form-control", rows: 3  %>
        </div>
    </div>
    <div class="card-footer">
        <%= form.submit class: "btn btn-primary" %>
    </div>

</div>


<% end %>

app/views/posts/edit.html.erb
<div class='post-form'>
    <h1><%= t('.title') %></h1>

    <%= render 'form', post: @post %>
</div>

app/views/posts/increase_like.js.erb
alert('Vou atualizar o like');
$("#post-<%= @post.id %>").html("<%= escape_javascript(render partial: 'boards/increase_like', locals: { post: @post, widget: @widget } ) %>");

app/views/posts/new.html.erb
<div class='post-form'>
    <h1><%= t('.title') %></h1>

    <%= render 'form', post: @post %>
</div>